services:
  - type: web
    name: makkisportfolio
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "gunicorn makkisportfolio.wsgi"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
