# Generated by Django 5.2 on 2026-05-24 13:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="category",
            field=models.CharField(
                choices=[
                    ("web", "Web Apps"),
                    ("mobile", "Mobile"),
                    ("design", "Design"),
                ],
                default="web",
                max_length=20,
            ),
        ),
    ]
